esphome:
  min_version: 2025.2.0
  name: smartspeaker-bathroom
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
  # use priority 250 so gpio and i2c dac is setup before volume is set
    priority: 250
    then:
    ## Set a volume limit just to be safe...
    - media_player.volume_set:
        id: louder_mediaplayer
        volume: 10%

esp32:
  board: upesy_wrover
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"  
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y" 

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y" 
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5 

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API

api:

ota:
  platform: esphome
  password: !secret ota_password_smartspeaker-bathroom


### Optional if you want ethernet (then remove all wifi config) ###
ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO05
  interrupt_pin: GPIO35
  reset_pin: GPIO14

  manual_ip:
    static_ip: !secret static_ip_smartspeaker-bathroom
    gateway: !secret manual_ip_gateway
    subnet: !secret manual_ip_subnet
    dns1: !secret manual_ip_dns1
    dns2: !secret manual_ip_dns2

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://mrtoy-me/esphome-components-test@main
    components: [ tas5805m ]
    refresh: 0s

i2c:
  id: i2c_component
  sda: GPIO21
  scl: GPIO27
  scan: True
  frequency: 400kHz
  timeout: 10ms

audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO33

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO22
    audio_dac: tas5805m_dac
    channel: stereo
    sample_rate: 48000
    buffer_duration: 60ms

media_player:
  - platform: speaker
    name: Louder Mediaplayer
    id: louder_mediaplayer
    volume_increment: 0.5%
    volume_min: 45%
    volume_max: 80%
    announcement_pipeline:
      speaker: speaker_id
    buffer_size: 100000
    on_play:
      if:
        condition:
          switch.is_off: enable_louder
        then:
          switch.turn_on: enable_louder
    on_announcement:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder

switch:
  - platform: template
    name: Enable Louder
    id: enable_louder
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - lambda:  |-
          id(tas5805m_dac).set_deep_sleep_off();
    turn_off_action:
      - lambda:  |-
          id(tas5805m_dac).set_deep_sleep_on();

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - switch.is_on: enable_louder
            - for:
                time: 60s
                condition:
                  or:
                    - media_player.is_idle: louder_mediaplayer
                    - media_player.is_paused: louder_mediaplayer
          then:
            - switch.turn_off: enable_louder
