esphome:
  min_version: 2025.2.0
  name: esp32-louder
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
  # use priority 250 so gpio and i2c dac is setup before volume is set
    priority: -100
    then:
    ## Set a volume limit just to be safe...
    - media_player.volume_set:
        id: louder_mediaplayer
        volume: 5%

esp32:
  board: upesy_wrover
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password_smartspeaker-bathroom

ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO05
  interrupt_pin: GPIO35
  reset_pin: GPIO14

  manual_ip:
    static_ip: !secret static_ip_smartspeaker-bathroom
    gateway: !secret manual_ip_gateway
    subnet: !secret manual_ip_subnet
    dns1: !secret manual_ip_dns1
    dns2: !secret manual_ip_dns2


globals:
  - id: current_volume
    type: float

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://mrtoy-me/esphome-components-test@main
    components: [ tas5805m ]
    refresh: 0s

i2c:
  id: i2c_component
  sda: GPIO21
  scl: GPIO27
  frequency: 400kHz
  scan: True

audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO33

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO22
    audio_dac: tas5805m_dac
    channel: stereo
    sample_rate: 48000
    timeout: never
    buffer_duration: 100ms

  - platform: mixer
    id: mixer_speaker_id
    task_stack_in_psram: true
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
        timeout: never
      - id: media_spk_mixer_input
        timeout: never

  - platform: resampler
    id: media_spk_resampling_input
    task_stack_in_psram: true
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampling_input
    task_stack_in_psram: true
    output_speaker: announcement_spk_mixer_input

media_player:
  - platform: speaker
    name: Louder Mediaplayer
    id: louder_mediaplayer
    task_stack_in_psram: true
    volume_increment: 0.5%
    volume_min: 45%
    volume_max: 80%
    media_pipeline:
      speaker: media_spk_resampling_input
      num_channels: 2
    announcement_pipeline:
      speaker: announcement_spk_resampling_input
      num_channels: 1

    on_play:
      if:
        condition:
          switch.is_off: enable_louder
        then:
          switch.turn_on: enable_louder

    on_announcement:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder
      - lambda: |-
          id(current_volume) = id(tas5805m_dac).volume();
      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 40
            duration: 0.0s
      - wait_until:
            media_player.is_announcing:
      - delay: 1.0s
      - lambda: |-
          id(tas5805m_dac).set_volume(id(announce_volume).state / 100);
      - wait_until:
          not:
            media_player.is_announcing:
      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 0
            duration: 2.0s
      - lambda: |-
          id(tas5805m_dac).set_volume(id(current_volume));

number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 50
    optimistic: true

switch:
  - platform: template
    name: Enable Louder
    id: enable_louder
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - lambda: !lambda |-
          id(tas5805m_dac).set_deep_sleep_off();
    turn_off_action:
      - lambda: !lambda |-
          id(tas5805m_dac).set_deep_sleep_on();

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - switch.is_on: enable_louder
            - for:
                time: 300s
                condition:
                  or:
                    - media_player.is_idle: louder_mediaplayer
                    - media_player.is_paused: louder_mediaplayer
          then:
            - switch.turn_off: enable_louder
